// services/scrapers/indeedScraperPy.js
const { spawn } = require('child_process');
const path = require('path');
const fs = require('fs');

/**
 * Scrapes Indeed Jobs using a Python script
 * @param {string} role - Job role to search for
 * @param {string} location - Location to search in
 * @param {number} numJobs - Number of jobs to request from the scraper
 * @returns {Promise<Array>} - Array of job objects
 */
const scrapeIndeedJobsPy = async (role, location, numJobs = 50) => {
  return new Promise((resolve, reject) => {
    console.log(`Starting Indeed jobs scraper for: ${role} in ${location}`);
    
    const scriptPath = path.join(__dirname, 'indeedScraper.py');
    console.log(`Script path: ${scriptPath}`);
    
    // Check if script exists
    if (!fs.existsSync(scriptPath)) {
      console.error(`Python script not found at ${scriptPath}`);
      return resolve([]);
    }
    
    // Use system Python
    const pythonProcess = spawn('python', [scriptPath, role, location, String(numJobs)]);
    
    let dataString = '';
    
    pythonProcess.stdout.on('data', (data) => {
      dataString += data.toString();
      console.log(`Python output: ${data}`);
    });
    
    pythonProcess.stderr.on('data', (data) => {
      console.error(`Python error: ${data}`);
    });
    
    // Handle process completion
    pythonProcess.on('close', (code) => {
      console.log(`Python process exited with code ${code}`);
      
      if (code !== 0) {
        console.error(`Python script exited with error code ${code}`);
        return resolve([]);
      }
      
      try {
        // Determine the full path to the output file
        const outputFilePath = path.join(process.cwd(), 'indeed_jobs.json');
        console.log(`Looking for Indeed jobs data at: ${outputFilePath}`);
        
        // Check if the file exists
        if (!fs.existsSync(outputFilePath)) {
          console.error(`Output file not found at ${outputFilePath}`);
          return resolve([]);
        }
        
        // Get file stats
        const stats = fs.statSync(outputFilePath);
        console.log(`File size: ${stats.size} bytes`);
        
        if (stats.size === 0) {
          console.error('Output file exists but is empty');
          return resolve([]);
        }
        
        // Read the JSON file generated by the script
        const jobsData = fs.readFileSync(outputFilePath, 'utf8');
        console.log(`Read ${jobsData.length} characters from file`);
        
        if (!jobsData || jobsData.trim() === '') {
          console.error('File content is empty');
          return resolve([]);
        }
        
        // Try to parse the JSON
        try {
          const jobs = JSON.parse(jobsData);
          console.log(`Successfully parsed JSON with ${jobs.length} jobs`);
          
          // Format jobs to match our expected structure
          const formattedJobs = jobs.map(job => ({
            id: job.id || `indeed-${Date.now()}-${Math.random().toString(36).substring(7)}`,
            title: job.title || 'Unknown Title',
            company: job.company || 'Unknown Company',
            location: job.location || location,
            description: job.description || 'No description available',
            url: job.url || '#',
            source: 'Indeed',
            time_posted: job.time_posted || 'Recently',
            created: new Date().toISOString(),
            salary: job.salary || 'Not specified'
          }));
          
          console.log(`Successfully processed ${formattedJobs.length} Indeed jobs`);
          resolve(formattedJobs);
        } catch (parseError) {
          console.error('Error parsing JSON:', parseError);
          console.error('First 100 characters of file:', jobsData.substring(0, 100));
          resolve([]);
        }
      } catch (error) {
        console.error('Error reading or processing Indeed jobs data:', error);
        resolve([]);
      }
    });
    
    // Handle process error
    pythonProcess.on('error', (error) => {
      console.error('Failed to start Python process:', error);
      resolve([]);
    });
  });
};

module.exports = {
  scrapeIndeedJobsPy
};
